### ISSUE TITLE
Easy way to change radius

### ISSUE THREAD

**Issue by theoryshaw** [hlorus/geometry_sketcher#1]
Love this plugin!

I'm excited about [this conversation](https://community.osarch.org/discussion/731/geometry-sketcher) and the potential integration to BlenderBIM, as well.

...

Would be nice to be able to change the radius, after the fact, and on the fly. Something like this UI...

![image](https://user-images.githubusercontent.com/507113/133931578-5a161d99-3a6a-4f11-a9ee-b79df8530255.png)

**Comment by hlorus** [comment]
Hey there, 
Thanks for the mockup! Are you asking for a way to enter the radius while drawing an arc segment? Otherwise i don't really understand what you mean, why wouldn't you just make a diameter constraint?

**Comment by theoryshaw** [comment]
Ah, got it!  Newbie user. didn't see that functionality. awesome.
