### ISSUE TITLE
GS crashes when converting to mesh

### ISSUE THREAD

**Issue by theoryshaw** [hlorus/geometry_sketcher#15]
Video: https://www.dropbox.com/s/g2ylsoepr29ehpn/2022-02-17_18-28-00.mp4?dl=0

Blender 3.0
GS: 02/17/2022

**Comment by hlorus** [comment]
Thanks for reporting. Unfortunately i cannot reproduce this crash reliably.

**Comment by hlorus** [comment]
Could you provide the crash report? https://docs.blender.org/manual/en/latest/troubleshooting/crash.html#:~:text=%2Do%20%25MEM%20.-,Crash%20Log,as%20some%20other%20debug%20information.

**Comment by hlorus** [comment]
Seems to be fixed, feel free to reopen if the crash persists.
