### ISSUE TITLE
Interactive dimensions

### ISSUE THREAD

**Issue by theoryshaw** [hlorus/geometry_sketcher#2]
Related to #1 

would be nice to quickly change the dimension on segments as well... 

Perhaps, being able to 'move' the dimension to indicate which segment you'd like to measure off of. 

![image](https://user-images.githubusercontent.com/507113/133932335-a99fb43d-f7b3-4d0d-85cc-8b5ec2d3d257.png)

![image](https://user-images.githubusercontent.com/507113/133932387-44ad277c-50f7-4b23-ab5c-b2f042577aaf.png)

**Comment by hlorus** [comment]
Hey, i assume you're looking for the distance constraint. :)

**Comment by theoryshaw** [comment]
Maybe. :)  I see that, but not quite sure how it works, yet. 

video: https://www.dropbox.com/s/49qso0ortut1g2d/2021-09-20_09-31-58.mp4?dl=0

**Comment by hlorus** [comment]
Unfortunately this isn't yet documented. As of now a distance constraint is always between a point and a point/line/workplane.

If you're not sure how it works it's best to deselect everything, hit the button in the sidebar and follow the instructions in the statusbar.

**Comment by theoryshaw** [comment]
nice... got it!  
When adjusting the dimension, is there anyway to constrain one edge, so the distance changes in one direction only? verses 2 directions, as illustrated in the video below.

video: https://www.dropbox.com/s/jjmd2wcicmchu99/2021-09-20_10-15-14.mp4?dl=0

**Comment by hlorus** [comment]
When creating a sketch there should be a fixed point at the origin, it's good practice to define the location to the origin. Alternatively you can right click on a point and fix it.

**Comment by theoryshaw** [comment]
very cool.. Thanks for taking me through this. 
Will you use this repo for documentation too?  If so, I can help with PR's here and there.

**Comment by hlorus** [comment]
> very cool.. Thanks for taking me through this.
> Will you use this repo for documentation too? If so, I can help with PR's here and there.

I plan to use github wiki for the documentation. Maybe we can discuss the topic on discord?

**Comment by theoryshaw** [comment]
Sure!  Since you're in the early days, i would suggest using [Element.io](https://app.element.io/) instead of Discord.  It's open source. :)
Also the [OSarch](https://community.osarch.org/) community uses it all the time, [here](https://app.element.io/#/room/#OSArch:matrix.org).  I could see some awesome cross ferritization happening with that group.
